version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: config/dev/Dockerfile
    volumes:
      # Source code file
      - ./source/:/var/www/html/
      - ./source/storage/app/public/:/var/www/html/public/storage/

    ports:
      - target: 8080
        published: 11103
        mode: ingress

    # Limit default logging container
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        mode: non-blocking
  nginx:
      image: nginx:alpine
      container_name: laravel-nginx
      restart: unless-stopped
      ports:
        - "8000:80"
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./:/var/www/html
      depends_on:
        - web
networks:
  default:
    name: main-network
    external: true