version: '3.8'

services:
  web_service:
    image: ${IMAGE_REPO_NAME}:${IMAGE_TAG}
    ports:
      - target: 8080
        published: 10161
        mode: ingress
    volumes:
      - ./source/storage:/var/www/html/storage
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
