name: Docker Image CI for GHCR
on:
  push:
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image artha_medica
        run: |
          docker login ghcr.io --username meteor95 --password ${{ secrets.SEIRA_ERAYA_DIGITAL }}
          docker build . --tag ghcr.io/meteor95/artha_medica-ghcr:latest
          docker push ghcr.io/meteor95/artha_medica-ghcr:latest
          
